---
apiVersion: v1
kind: Service
metadata:
  name: filebeat-syslog
  namespace: efk
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    release: filebeat
