apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: structured-logging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: structured-logging
  template:
    metadata:
      labels:
        app: structured-logging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port:  "8080"
    spec:
      containers:
        - image: alexandreroman/spring-boot-structured-logging-demo
          name: app
          resources:
            limits:
              memory: 1Gi
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 60
            periodSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
