---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: structured-logging
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: structured-logging
